install:
	@go get github.com/spf13/hugo

# Build the website
publish:
	hugo --destination ../
	# TODO there's more here
	# https://gohugo.io/tutorials/github-pages-blog/#deployment-via-gh-pages-branch

# Serve the Funnel website on localhost:1313
dev:
	hugo -w server
